[tool.poetry]
name = "Scrapy work.ua"
version = "0.1.0"
description = "homework №20"
authors = ["Evgeniy"]

[tool.poetry.dependencies]
python = "^3.8"
Scrapy = "^2.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
